print ("hello world")
print ("Hello Again")
print ("I like typing this.")
print ("this is fun")
print ("yay! Printing.")
print ("I'd much rather you 'not'.")
print ('I "said" do not thouch this.')
print ('11/20 successfully print out this file in the Terminal! feeling good!')
# print ("try to type # at the beginning of a line")